### ISSUE TITLE
[Bug] [kompile] - Single comment at end of file causes kompile error

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/k#2373]
K Version
---------

```
K version:    v5.2.21-17-g44ebd7036
Build date:   Tue Dec 07 10:52:28 CET 2021
```

Description
-----------
Kompiling a file that ends in a single line comment (i.e. `//`) causes an error.

Input Files
-----------
File `foo.k`
```
module FOO

endmodule
//
 ```

Reproduction Steps
------------------
Make sure that the last line of the file starts with `//`.
```
kompile foo.k
```
Output:
```
[Error] Outer Parser: Lexical error at line 4, column 3.  Encountered: <EOF>
after : "//" (TokenMgrException: Lexical error at line 4, column 3. 
Encountered: <EOF> after : "//")
```

Expected Behavior
-----------------
To compile without an error.

**Comment by radumereuta** [comment]
We should modify this line to allow for this: https://github.com/kframework/k/blob/master/kernel/src/main/javacc/Outer.jj#L404

**Comment by radumereuta** [comment]
You can add a Unit test here: https://github.com/kframework/k/blob/master/kernel/src/test/java/org/kframework/parser/inner/RuleGrammarTest.java#L521
To build K faster you can use this command to skip the unit tests: `mvn package -DskipTests`

**Comment by Baltoli** [comment]
I see that the parser generator acknowledges that this is a limitation in JavaCC:
```java
/* BUGS:

Due to now JavaCC handles EOF, EOF cannot terminate a single-line comment
...
*/
```

@dwightguth is this something that would have been likely to ever have been fixed?

We could also implement a check that files are terminated with a newline; doing so would catch this with a friendlier error message.

**Comment by ehildenb** [comment]
It could be as simple as checking if update to JavaCC fixes this.

**Comment by radumereuta** [comment]
I just tested this with
```xml
<groupId>org.codehaus.mojo</groupId>
<artifactId>javacc-maven-plugin</artifactId>
<version>3.0.1</version>
```
and
```xml
<groupId>com.helger.maven</groupId>
<artifactId>ph-javacc-maven-plugin</artifactId>
<version>4.1.5</version>
```
And the issue persists.
I would not bother fixing this.
The error message is clear enough to avoid it. We can accept such a limitation.

**Comment by dwightguth** [comment]
I looked into this and it appears that the issue is that the way we are specifying the regex for comments is that we expect a comment to end with \n or \r. In theory we could probably modify the way we handle comments in outer parsing so we used lexical states to deal with comments, which would likely fix this issue. However, we are already using lexical states when parsing comments in a way I don't fully understand, so I would tend to agree this is probably not worth trying to fix.

We can leave it open, just putting it in the backlog.
